### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by matiasmascioto** [And7s/soccer-analysis#1]
Where is it possible to download the input data? Thanks.

**Comment by And7s** [comment]
Hello matiasma, 
unfortunately I do not own the data for this research paper. The data is owned by the company that collects it and collaborates with the chair at my university for research purposed, but do not allow public distribution.

I would advice you to send me a email and I can get you in contact with my supervisor. As by now this project is almost two years old they might consider releasing the data.

my mail is firstname lastname @ gmx.net (no spaces, you find my first/ lastname in the paper, just to avoid spam)
